[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "goes-manager"
version = "0.1.0"
description = "Tools for monitoring and managing GOES satellite ground-station data"
readme = "readme.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [
  { name = "Jared" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: POSIX :: Linux",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
